COURSE_ACTS(COURSE_BOB, _(" 1 FRENTE BOB-OMB"),
       _("REY BOB-OMB EN LA CIMA")     , _("CARRERA CON KOOPA EL RAPIDO") , _("CANONAZO A LA ISLA EN EL CIELO"),
       _("ENCUENTRA LAS 8 MONEDAS ROJAS")          , _("MARIO ALADO POR EL CIELO")        , _("TRAS LAS REJAS DE CHOMP CADENAS"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALEZA ROCO"),
       _("DERROTA AL REY ROCO")        , _("EN LO MAS ALTO DE LA FORTALEZA")    , _("CANONAZO AL CIELO"),
       _("MONEDAS ROJAS EN LA ISLA FLOANTE"), _("CAE EN LA ISLA ENJAULADA")    , _("REVIENTA LA PARED"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAHIA PIRATA"),
       _("SAQUEA EL BARCO HUNDIDO")    , _("  PUEDE SALIR LA ANGUILA A JUGAR?") , _("TESORO DE LA CUEVA DEL OCEANO"),
       _("MONEDAS ROJAS EN EL BARCO FLOTANTE")  , _("CANONAZO AL PILAR DE PIEDRA")     , _("A CONTRACORRIENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTANA HELADA"),
       _("RESBALATE Y DESLIZATE")             , _("PEQUENO PINGUINO PERDIDO")             , _("CARRERA CONTRA EL GRAN PINGUINO"),
       _("MONEDAS ROJAS EN EL TOBOGAN REFRESCANTE")  , _("EL MUNECO DE NIEVE HA PERDIDO LA CABEZA")       , _("LOS SALTOS EN PARED TE SERVIRAN"))

COURSE_ACTS(COURSE_BBH, _(" 5 GRAN SUSTO BOO"),
       _("CAZAFANTASMAS")            , _("SUBE AL TIOVIVO DEL GRAN BOO") , _("SECRETO DE LOS LIBROS ENCANTADOS"),
       _("BUSCA LAS 8 MONEDAS ROJAS")          , _("EL BALCON DEL GRAN BOO")             , _("OJO POR OJO EN LA SALA OCULTA"))

COURSE_ACTS(COURSE_HMC, _(" 6 CUEVA LABERINTICA"),
       _("MONSTRUO NADADOR EN LA CAVERNA")  , _("ELEVATE A POR LAS 8 MONEDAS")       , _(" MARIO METALERO SE MUEVE!"),
       _("NAVEGA EL LABERINTO TOXICO")     , _("SALIDA DE EMERGENCIA DEL LABERINTO")     , _("PELIGRO DE DESPRENDIMIENTO"))

COURSE_ACTS(COURSE_LLL, _(" 7 TIERRA DE LAVA LETAL"),
       _("HIERVE AL GRAN BULLY")            , _("HAZLE BULLYING A LOS BULLIES")             , _("8 MONEDAS ROJAS, 15 PIEZAS DE PUZZLE"),
       _("TRONCO ARDIENTE Y RODANTE")           , _("DE CABEZA AL VOLCAN")  , _("TOUR DE ASCENSORES EN EL VOLCAN"))

COURSE_ACTS(COURSE_SSL, _(" 8 ARENAS CAMBIANTES"),
       _("EN LOS TALONES DE LA GRAN AVE") , _("RELUCE EN LO ALTO DE LA PIRAMIDE")      , _("DENTRO DE LA ANTIGUA PIRAMIDE"),
       _("PISA LOS CUATRO PILARES"), _("VUELO LIBRE POR 8 MONEDAS ROJAS")   , _("PUZZLE PIRAMIDAL"))

COURSE_ACTS(COURSE_DDD, _(" 9 MUELLE DESOLADO"),
       _("INVADE EL SUBMARINO DE BOWSER")            , _("COFRES EN LA CORRIENTE")         , _("MONEDAS ROJAS DE PALO EN PALO"),
       _("A CONTRACORRIENTE")        , _("LA RECOMPENSA DE LA MANTA")        , _("CONSIGUE LAS GORRAS..."))

COURSE_ACTS(COURSE_SL, _("10 PAIS MUNECO DE NIEVE"),
       _("EL CABEZON DEL MUNECO DE NIEVE")            , _("REFRESCATE CON EL BULLY")          , _("CONGELAMIENTO PROFUNDO"),
       _("TORBELLINO DESDE EL LAGO HELADO")  , _("8 MONEDAS ROJAS EN CAPARAZON") , _("DENTRO DEL IGLU"))

COURSE_ACTS(COURSE_WDW, _("11 MUNDO MOJASECA"),
       _(" ASCENSORES ELECTRIFICANTES!")         , _("EN LO ALTO DEL PUEBLO")               , _("SECRETOS EN LOS HUECOS Y EL CIELO"),
       _("ASCENSOR EXPRESS -  DATE PRISA!")   , _("VETE AL PUEBLO A POR MONEDAS ROJAS")      , _(" A TODA PRISA POR EL PUEBLO!"))

COURSE_ACTS(COURSE_TTM, _("12 MONTANA SUBE-SUBE"),
       _("ESCALA LA MONTANA")            , _("EL MISTERIO DE LA JAULA DEL MONO")    , _("CHAMPINONES ESCALOFRIANTES, MONEDAS ROJAS"),
       _("EL LADO MISTERIOSO DE LA MONTANA")       , _("VISTA INCREIBLE DESDE EL PUENTE") , _("CANONAZO AL CHAMPINON SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 ISLA CAMBIANTE"),
       _("ARRANCA LA PLANTA PIRANA")      , _("LA CIMA DE LA ISLA GIGANTE"), _("REVANCHA DE KOOPA EL RAPIDO"),
       _("CINCO SECRETITOS DE NADA")       , _("LAS MONEDAS ROJAS DE WIGGLER")           , _("HAZ QUE WIGGLER SE RETUERZA"))

COURSE_ACTS(COURSE_TTC, _("14 RELOJ TIC TAC"),
       _("SALTA A LA JAULA")            , _("EL VACIO Y LOS PENDULOS")     , _("  TE ECHO UNA MANECILLA?"),
       _("PISOTEA AL THWOMP")           , _("SALTOS PRECISOS EN LAS BARRAS")    , _("PARA EL TIEMPO, CONSIGUE MONEDAS ROJAS"))

COURSE_ACTS(COURSE_RR, _("15 CAMINO DEL ARCOIRIS"),
       _("CRUCERO POR EL ARCOIRIS")  , _("LA GRAN CASA EN EL CIELO")      , _("MONEDAS EN EL LABERINTO"),
       _("SALTANDO POR LAS CORRIENTES")        , _(" TRIANGULOS CON TRUCO!")             , _("POR ENCIMA DEL ARCOIRIS"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER EN EL MUNDO OSCURO"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER EN EL MAR DE FUEGO"))
SECRET_STAR(COURSE_BITS, _("   BOWSER EN EL CIELO"))
SECRET_STAR(COURSE_PSS, _("   EL TOBOGAN SECRETO DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA DE LA GORRA DE METAL"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DE LA GORRA VOLADORA"))
SECRET_STAR(COURSE_VCUTM, _("   FOSO DE LA GORRA DE INVISIBILIDAD"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO ALADO SOBRE EL ARCOIRIS"))
SECRET_STAR(COURSE_SA, _("   EL ACUARIO SECRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELLAS SECRETAS"))

EXTRA_TEXT(0, _(" UNA DE LAS ESTRELLAS SECRETAS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
